### ISSUE TITLE
noun + adjective -> verb

### ISSUE THREAD

**Issue by ghost** [gnull/mess#1]
Set of Utilities for Backuping vk.com Messages -> Set of Utilities for Backing Up vk.com Messages

**Comment by gnull** [comment]
Да, так, наверное, и правда лучше звучит, сейчас изменю.

Я, когда писал это, не нашёл нужного значения глагола «back up» в словаре и решил, что он не употребляется в смысле «делать резервную копию» как «backup». Оказывается, тот словарь был плохой, сейчас я заглянул в другой и там это значение есть.
